services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    restart: unless-stopped

  # # Optional Locust load testing service
  # locust:
  #   image: locustio/locust
  #   ports:
  #     - "8089:8089"
  #   volumes:
  #     - ./locust:/locust
  #   command: -f /locust/locustfile.py --host http://web:5000
  #   depends_on:
  #     - web