services:
  # Flask Web App (Updated start command to use `waitress`)
  - type: web
    name: heart-disease-flask
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m waitress --host 0.0.0.0 --port $PORT src.app:app

  # FastAPI Service (No change needed)
  - type: web
    name: heart-disease-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn src.api:app --host 0.0.0.0 --port $PORT