services:
  # Flask Web Application
  - type: web
    name: heart-disease-flask
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-tmp-dir /dev/shm --bind 0.0.0.0:$PORT src.app:app
    envVars:
      - key: DATABASE_URL
        value: postgresql://root:kp0rW6ieadQrvsb4RGR1XUyvaaguwaCb@dpg-cvm3tdp5pdvs739gh7mg-a.oregon-postgres.render.com/heart_database_p3mz
      - key: FASTAPI_URL
        value: https://heart-disease-api.onrender.com

  # FastAPI Service
  - type: web
    name: heart-disease-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn src.api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: postgresql://root:kp0rW6ieadQrvsb4RGR1XUyvaaguwaCb@dpg-cvm3tdp5pdvs739gh7mg-a.oregon-postgres.render.com/heart_database_p3mz